# Linux makefile for FreeImage

# This file can be generated by ./gensrclist.sh
include Makefile.srcs

# LibJXR's bundled sources use Windows-only SAL/GUID headers (matching
# CMakeLists.txt's own BUILD_JXR default of WIN32-only) - exclude them from
# the Linux build rather than fail to compile.
SRCS := $(filter-out Source/LibJXR/%, $(SRCS))

# General configuration variables:
DESTDIR ?= /
INCDIR ?= $(DESTDIR)/usr/include
INSTALLDIR ?= $(DESTDIR)/usr/lib

# Converts cr/lf to just lf
DOS2UNIX = dos2unix

LIBRARIES = -lstdc++

MODULES = $(SRCS:.c=.o)
MODULES := $(MODULES:.cpp=.o)

# C flags
CFLAGS ?= -std=c99 -O3 -fPIC -fexceptions -fvisibility=hidden
# ZLib: needed for gzlib.c/gzread.c/gzwrite.c to see read()/write()/lseek()
# via zconf.h's Z_HAVE_UNISTD_H gate (normally set by zlib's own ./configure)
CFLAGS += -DHAVE_UNISTD_H
# OpenJPEG
CFLAGS += -DOPJ_STATIC
# LibRaw
CFLAGS += -DNO_LCMS
# LibJXR
CFLAGS += -DDISABLE_PERF_MEASUREMENT -D__ANSI__
CFLAGS += $(INCLUDE)

# C++ flags
# OpenEXR's IlmImf (ImfMultiPartInputFile.cpp) uses std::any, which needs
# C++17 - this is unconditionally in SRCS, so the whole build needs it.
CXXFLAGS ?= -std=c++17 -O3 -fPIC -fexceptions -fvisibility=hidden -Wno-ctor-dtor-privacy
# LibJXR
CXXFLAGS += -D__ANSI__
# OpenEXR, LibRaw, and WebP sources are unconditionally in SRCS, so tell
# PluginEXR.cpp/PluginRAW.cpp/PluginWebP.cpp to compile their real
# implementations instead of the disabled-build stub (see #38) - LibJXR is
# deliberately left out here since its sources are excluded above (Windows-
# only headers), so PluginJXR.cpp compiles its stub instead.
CXXFLAGS += -DINCLUDE_LIB_OPENEXR -DINCLUDE_LIB_RAW -DINCLUDE_LIB_WEBP
CXXFLAGS += $(INCLUDE)

ifeq ($(shell sh -c 'uname -m 2>/dev/null || echo not'),x86_64)
	CFLAGS += -fPIC
	CXXFLAGS += -fPIC
endif

TARGET  = freeimage
STATICLIB = lib$(TARGET).a
SHAREDLIB = lib$(TARGET)-$(VER_MAJOR).$(VER_MINOR).so
LIBNAME	= lib$(TARGET).so
VERLIBNAME = $(LIBNAME).$(VER_MAJOR)
HEADER = Source/FreeImage.h



default: all

all: dist

dist: FreeImage
	mkdir -p Dist
	cp *.a Dist/
	cp *.so Dist/
	cp Source/FreeImage.h Dist/

dos2unix:
	@$(DOS2UNIX) $(SRCS) $(INCLS)

FreeImage: $(STATICLIB) $(SHAREDLIB)

.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(STATICLIB): $(MODULES)
	$(AR) r $@ $(MODULES)

$(SHAREDLIB): $(MODULES)
	$(CC) -s -shared -Wl,-soname,$(VERLIBNAME) $(LDFLAGS) -o $@ $(MODULES) $(LIBRARIES)

install:
	install -d $(INCDIR) $(INSTALLDIR)
	install -m 644 -o root -g root $(HEADER) $(INCDIR)
	install -m 644 -o root -g root $(STATICLIB) $(INSTALLDIR)
	install -m 755 -o root -g root $(SHAREDLIB) $(INSTALLDIR)
	ln -sf $(SHAREDLIB) $(INSTALLDIR)/$(VERLIBNAME)
	ln -sf $(VERLIBNAME) $(INSTALLDIR)/$(LIBNAME)	
#	ldconfig

clean:
	rm -f core Dist/*.* u2dtmp* $(MODULES) $(STATICLIB) $(SHAREDLIB) $(LIBNAME)

